FROM public.ecr.aws/lambda/python:3.8

# Set the working directory to /app
WORKDIR /app

# Copy application code into the container
COPY . .

# Set the command to be run when the container starts
CMD ["s103878717.handler"]
